version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - APPLYDIRECTIVITY
  - deinterleaved
  - directivity
  - direnv
  - emscripten
  - EMSDK
  - esbuild
  - hrtf
  - HRTFINTERPOLATION
  - HRTFTYPE
  - IPLHRTF
  - kwaa
  - nixpkgs
  - pkgs
ignoreWords: []
import: []
