version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Ambi
  - ambisonic
  - ambisonics
  - antfu
  - APPLYDIRECTIVITY
  - bumpp
  - ccall
  - changelogithub
  - cwrap
  - deinterleaved
  - directivity
  - direnv
  - dont
  - drei
  - emcc
  - emscripten
  - EMSDK
  - esac
  - esbuild
  - flatc
  - HEAPF
  - HEAPU
  - hrtf
  - HRTFINTERPOLATION
  - HRTFTYPE
  - IPLHRTF
  - kwaa
  - libmysofa
  - libpffft
  - libz
  - moeru
  - mysofa
  - nixpkgs
  - pffft
  - pkgs
  - pname
  - seti
  - sonarjs
  - spatialization
  - stdenv
  - tsdown
  - uikit
  - vite
  - vitejs
  - vitest
  - viverse
ignoreWords: []
import: []
