version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ambisonics
  - antfu
  - APPLYDIRECTIVITY
  - deinterleaved
  - directivity
  - direnv
  - drei
  - emscripten
  - EMSDK
  - esbuild
  - HEAPF
  - HEAPU
  - hrtf
  - HRTFINTERPOLATION
  - HRTFTYPE
  - IPLHRTF
  - kwaa
  - moeru
  - nixpkgs
  - pkgs
  - sonarjs
  - spatialization
  - tsdown
  - vite
  - vitejs
  - vitest
  - viverse
ignoreWords: []
import: []
