allowBuilds:
  esbuild: false

minimumReleaseAge: 1440

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^9.0.0
  '@eslint-react/eslint-plugin': ^5.6.0
  '@moeru/eslint-config': 0.1.0-beta.18
  '@moeru/tsconfig': ^0.1.0-beta.18
  '@react-three/drei': ^10.7.7
  '@react-three/fiber': ^9.6.1
  '@react-three/uikit': ^1.0.73
  '@react-three/uikit-horizon': ^1.0.73
  '@react-three/viverse': ^0.2.20
  '@react-three/xr': ^6.6.30
  '@types/emscripten': ^1.41.5
  '@types/node': ^25.9.2
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  '@types/three': ^0.184.1
  '@vitejs/plugin-react': ^6.0.2
  eslint: ^10.3.0
  eslint-plugin-react-refresh: ^0.5.2
  leva: ^0.10.1
  r3f-perf: ^7.2.3
  react: ^19.2.7
  react-dom: ^19.2.7
  three: ^0.184.0
  tsdown: ^0.22.2
  typescript: ^6.0.3
  vite: ^8.0.16
  vitest: ^4.1.8
